name: Standard test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v3

      # Install node
      - name: Install NodeJS v16
        id: node
        if: steps.checkout.outcome == 'success'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Install deps
      - name: Install Dependencies
        id: install
        if: steps.node.outcome == 'success'
        run: yarn install
      
      # Run tests
      - name: Run tests
        id: tests
        if: steps.node.outcome == 'success'
        run: yarn test
